### ISSUE TITLE
t is not a function

### ISSUE THREAD

**Issue by Hiaguedes** [marmelab/json-graphql-server#131]
when i first run the project in 2.3.0 the server logged `t(...) is not a function`, i downgraded for 2.2.3 and worked just fine. So keep an eye on that new version

**Comment by colonaut** [comment]
Just to confirm, same here. Only solution is to downgrade to 2.2.3

**Comment by digeomel** [comment]
Same here 😞

**Comment by gabalicious** [comment]
> Just to confirm, same here. Only solution is to downgrade to 2.2.3

Did not work for me.  Running on an m1 w/ Node v14.8.2 and npm v8.3 (Also tried v14.7, v14.15 and v16.13.1).  Installed 14.x in intel architecture

**Comment by gabalicious** [comment]
> > Just to confirm, same here. Only solution is to downgrade to 2.2.3
> 
> Did not work for me. Running on an m1 w/ Node v14.8.2 and npm v8.3 (Also tried v14.7, v14.15 and v16.13.1). Installed node 14.x w/ intel architecture and 16 w/ apple silicon architecture

Anyone care to put what os they are running, node and npm versions they have to get this to work?

Hopefully that's enough to narrow down the issues.

**Comment by fzaninotto** [comment]
I can't replicate the problem in StackBlitz. Could you explain how to replicate it step-by-step?

**Comment by theArgex** [comment]
@fzaninotto 
Happened to me too locally with Node v17.3.0.

1. 

```
npm install -g json-graphql-server   
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 16 packages, removed 15 packages, changed 79 packages, and audited 96 packages in 8s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```
2. `json-graphql-server db.js --p 4200`
db.js:
```js
module.exports = {
    posts: [
        { id: 1, title: "Lorem Ipsum", views: 254, user_id: 123 },
        { id: 2, title: "Sic Dolor amet", views: 65, user_id: 456 },
    ],
    users: [
        { id: 123, name: "John Doe" },
        { id: 456, name: "Jane Doe" }
    ],
    comments: [
        { id: 987, post_id: 1, body: "Consectetur adipiscing elit", date: new Date('2017-07-03') },
        { id: 995, post_id: 1, body: "Nam molestie pellentesque dui", date: new Date('2017-08-17') }
    ]
}
```

3. Output:
Seems like the whole script itself with this error message at the end:
```
TypeError: t(...) is not a function
    at en (/usr/local/lib/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:2:1504746)
    at Object.<anonymous> (/usr/local/lib/node_modules/json-graphql-server/bin/json-graphql-server.js:26:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.3.0
```

For me v.2.2.3 also works with no issues. Thank you for your work.

**Comment by fzaninotto** [comment]
Reproduced, thanks

**Comment by fzaninotto** [comment]
I've reverted the changes pushed in 2.3.0 in 2.3.1, which should solve the problem.
