### ISSUE TITLE
write to db.js

### ISSUE THREAD

**Issue by rkristelijn** [marmelab/json-graphql-server#154]
I've tested this lib using `npx json-graphql-server db.js`. It works great! query works, inserts work, I see the new entries when when querying, but they are not persisted to db.js. Is there a way have the changes persisted to db.js?

**Comment by slax57** [comment]
No I don't think there is.
This libs purpose is mainly to help developers start a fake GraphQL server quickly, for testing purposes, but it's not meant to be used as a DB.
If you think this feature could be a nice addition, and are willing to work on it, I can leave this issue open as enhancement request if you want.

**Comment by rkristelijn** [comment]
I just wanted to make sure I didn't overlook an undocumented feature, for now you can close it. If we need it I'll reconsider working on it
