### ISSUE TITLE
Can this be used to mock Hasura GraphQL?

### ISSUE THREAD

**Issue by GiamBoscaro** [marmelab/json-graphql-server#159]
I was pretty happy to find this tool as I needed to mock Hasura when running my Unit Tests. I was able to make eveything work, but from what I see the GraphQL queries that are being generated are not the same as I have in Hasura, they're not following the same schema.
I am wondering if there's a way to make it work with Hasura. An example:

```graphql
# Query that runs with Hasura
query getAllErrors {
  errors {
    id
    title
    message
    status
  }
}
```

```graphql
# Query needed to run correctly
query getAllErrors {
  allErrors {
    id
    title
    message
    status
  }
}
```

Since my backend is using Hasura obviously I need the queries to work the same way, otherwise it is not a mock. Any suggestion?

**Comment by fzaninotto** [comment]
Great idea, although this would be a breaking change. As we want to avoid that, I'm afraid you have no other option but to fork our library and make a Hasura variant.
