### ISSUE TITLE
Save after mutation 

### ISSUE THREAD

**Issue by GurovDmitriy** [marmelab/json-graphql-server#171]
Сan I save my base after mutation operations like a json-server?

**Comment by slax57** [comment]
Just like with json-server, mutations are persisted to the in-memory copy of the data, but the original `db.js` file is not modified.

**Comment by BeautyLips** [comment]
The .json file is modified. Thanks for the answer anyway.
I'll install appolo and json-server. I'll write the resolvers myself). Add the ability to store, this is necessary for prototyping.

**Comment by GurovDmitriy** [comment]
The .json file is modified. Thanks for the answer anyway.
I'll install appolo and json-server. I'll write the resolvers myself). Add the ability to store, this is necessary for prototyping.
