### ISSUE TITLE
Firing a mutation does not update db.json

### ISSUE THREAD

**Issue by amite** [marmelab/json-graphql-server#19]
When I fire off a mutation like `createPost`, the action seems succeed but the changes only seem to be served from memory. `db.json` does not get updated. Isn't this contrary to expected behaviour?

**Comment by djhi** [comment]
No that's the expected behavior. As stated in the project description:
> Get a full **fake** GraphQL API with zero coding in less than 30 seconds.

This library is only meant to be used for easily testing GraphQL.
