### ISSUE TITLE
Multiline function arguments with trailing comma - SyntaxError: Unexpected token ) 

### ISSUE THREAD

**Issue by jdemangeon** [marmelab/json-graphql-server#20]
When I use a global install of "json-graphql-server" has it, I encounter an error because of trailing commas in multiline function arguments.

My version of Node is the following: **v7.1.0**. According to [this thread](https://github.com/nodejs/node/issues/11258), trailing comma support will be enabled by default in V8.

For the moment, I'm able to use the server with this command.

`node --harmony_trailing_commas /usr/lib/node_modules/json-graphql-server/bin/json-graphql-server.js`

Maybe we should remove them and adapt prettier rules (trailingComma) according to that ?

Anyway, thanks for this awesome work ! :+1:

**Comment by fzaninotto** [comment]
I agree, would you mind opening a PR changing the `prettier` rule and updating the affected files?

**Comment by jdemangeon** [comment]
Yes, the following PR will fix it.

https://github.com/marmelab/json-graphql-server/pull/21/files

**Comment by fzaninotto** [comment]
Fixed by #21
