### ISSUE TITLE
JSON to Schema

### ISSUE THREAD

**Issue by ritz078** [marmelab/json-graphql-server#22]
Can I use this to get a best guess GraphQL schema from a given JSON ? If yes I would love to add it on https://transform.now.sh/

**Comment by djhi** [comment]
Hi! Not in its current form but we can probably extract the part which guess the schema from the json data. I'll let you know

**Comment by ritz078** [comment]
thanks a lot. 🙏

**Comment by djhi** [comment]
Work is happening here: https://github.com/marmelab/json-to-graphql-schema.

I'll make a pull request on transform as soon as this is finished.

**Comment by ritz078** [comment]
This looks awesome 🙌
