### ISSUE TITLE
Serve the GraphiQL UI

### ISSUE THREAD

**Issue by kylecordes** [marmelab/json-graphql-server#42]
Although currently "the server is GraphiQL enabled", to use it appears to require standing up GraphiQL separately (perhaps via the electron app that is linked) and then pointing at this server.

Feature request:

Optionally (controlled by a switch) serve the GraphiQL UI from json-graphql-server.

**Comment by fzaninotto** [comment]
The GraphiQL interface *is* served by this package. Just open the url (http://localhost:3000) in a web browser to see it. 

If not, which version are you using? What do you see in the browser when you go to that URL?

**Comment by alexisjanvier** [comment]
I confirm that the GraphiQL interface is served.
