### ISSUE TITLE
Does not generate "ID"

### ISSUE THREAD

**Issue by JulianaAbreu** [marmelab/json-graphql-server#43]
Hello, 
json-server can generate an ID when creating an entity, the json-graphql-server do this too?

**Comment by fzaninotto** [comment]
Yes!

**Comment by EricTousignant** [comment]
It doesn't seem to work for me.

I'm using json-graphql-server and I get this error message when trying to create an Addon:
```
Field "createAddon" argument "id" of type "ID!" is required but not provided.
```

**Comment by wagnerpaz** [comment]
Same problem here. I don't know how to auto increment ids.
