### ISSUE TITLE
Nested JSON - One-to-Many / Many-to-Many Relationship

### ISSUE THREAD

**Issue by mozark24** [marmelab/json-graphql-server#45]
Great project!  This seems very useful for developing the schema from a JSON.  I have an appropriately labeled JSON file that is 3 levels deep, each with a unique ID.  Right now it does not appear that the parser identifies properties further than the 2nd level.  Everything past that point is listed as type "JSON" and pulls as a group.

For example, in the below request it does not recognize everything below "Class" as having unique queriable properties.  You can only query the JSON chunk

```
{
  "School": [ {
    "id": 1,
    "name": "blah",
    "Class": [ {
         "id": 101,
         "Student": [ {
              "id": 501,
              "propertyA": "test"
         }]
     }]
  }]
}
```

```
{
  School(id: 1) {
    Class
  }
}
```

I would like to request only "propertyA" or other properties of the appropriate level while preserving the hierarchical relationship.

**Comment by fzaninotto** [comment]
Nice idea, but it's too complex to implement. It implies creating a structure that aggregates all the possible structures of this kind of JSON.

If you want to give it a go, be my guest, but we won't implement it ourselves.
