### ISSUE TITLE
Update mutation returns null and doesn't update anything

### ISSUE THREAD

**Issue by FrediBach** [marmelab/json-graphql-server#49]
This is my query and variables:

![updatewing](https://user-images.githubusercontent.com/871551/42216703-047a894e-7ec3-11e8-9616-1553d69b4fbf.png)

I previously added that wing with a create mutation, that works nicely. This is my original data for wings:

```
wings: [
        { id: 'ozone-zeno', model: 'Zeno', brand: 'Ozone', certification: 'D' },
        { id: 'nova-mentor-3', model: 'Mentor 3', brand: 'Nova', certification: 'B' }
],
```

**Comment by FrediBach** [comment]
Ah, guess that's the problem in update.js:

![update-ids](https://user-images.githubusercontent.com/871551/42217026-fb475284-7ec3-11e8-85f2-99d4a0c7bfda.png)

As my keys are strings, this of course wont work.

**Comment by fzaninotto** [comment]
Indeed, json-graphql-server only supports integer ids for now.

**Comment by fzaninotto** [comment]
cf #51

**Comment by boazblake** [comment]
should I be able to update / create new items or is this only for testing purposes? I am able to query my data but not update or post new
