### ISSUE TITLE
TypeError: jsonGraphqlExpress is not a function

### ISSUE THREAD

**Issue by oktalk** [marmelab/json-graphql-server#54]
Regardless of wether I use Node `require` or ES6 `import` with `node --experimental-modules server.mjs` I keep getting the error `TypeError: jsonGraphqlExpress is not a function` when setting up a Node server. Any ideas on how to resolve this?

I am able to run the `json-graphql-server` globally though, and I must say it's awesome. You all are doing great work. Keep it up.

**Comment by percysoft** [comment]
hello friend,the problem is for jsonGraphqlExpress is not function is un object which the function is inside of such object.
the solution is to write app.use ('/ graphql', jsonGraphqlExpress.default (data));
I hope to help

**Comment by alexisjanvier** [comment]
Thanks @percysoft  for your answer.

**Comment by justin-barca-at-camis** [comment]
I think this issue should be still open until the documentation is fixed as per recent reference.
