### ISSUE TITLE
Specified port not being used

### ISSUE THREAD

**Issue by oktalk** [marmelab/json-graphql-server#55]
Running `json-graphql-server db.js --p 4000` does not open the server in a different port. The port remains at `3000`.

**Comment by HardikModha** [comment]
@oktalk Seems like the functionality to specify the custom port is merged in the master but not released yet. The last release [v2.1.1](https://github.com/marmelab/json-graphql-server/releases/tag/v2.1.1) was made 8 months ago which did not have this functionality. Ability to specify the custom port support was added 4 months back in https://github.com/marmelab/json-graphql-server/commit/fd05e9e320609260de1ba2da1983c7bfb0e64b9c commit. 

/cc @fzaninotto @djhi

**Comment by fzaninotto** [comment]
version 2.1.2 was released today with that change.
