### ISSUE TITLE
removing by nonexisting ID deletes the last "record"

### ISSUE THREAD

**Issue by robertbbb** [marmelab/json-graphql-server#66]
Hi,

It seems that the remove Mutation, if it receives a nonexisting ID, will still remove something (at random?)

Otherwise thanks for a great tool.

**Comment by pjweisberg** [comment]
From what I'm seeing, the remove mutation deletes the last record regardless of whether the ID exists or not.

**Comment by pjweisberg** [comment]
I'm using version 2.1.3 from npm.  If I start it with this data file:

```
module.exports = {
  Orders: [
    {
      id: '12345',
      employeeName: 'Evert Flatley',
      status: 'DONE',
    },
    {
      id: '12346',
      status: 'BLOCKED',
    },
    {
      id: '12347',
      status: 'DONE',
    },
  ],
};
```

then I run this mutation in GraphiQL:
```
mutation {
  removeOrder(id: "12345")
}
```

I get this response:

```
{
  "data": {
    "removeOrder": null
  }
}
```

Then I query for all orders again, and 12347 (the last one) is missing.  12345 (the one I told it to delete) is still there.

**Comment by svey** [comment]
👍 I also have this issue although for me it occurs even when the id is correct.

**Comment by svey** [comment]
I just figured it out... the id attributes in your data files must be integers! @pjweisberg @robertbbb !!

**Comment by svey** [comment]
Unfortunately, if you create and then attempt to remove something you will response will be

```{
  "data": {
    "something": null
  }
}```

**Comment by pjweisberg** [comment]
Interesting.  Still a bug, but I guess that reduces the "how did anyone ever miss this?" factor.  IDs still come out as strings in the query responses, which I why I didn't think of changing to integers.

In the real world IDs will frequently be UUIDs (or at least alphanumeric), but in my current project I can get away with assuming they're integers.

**Comment by svey** [comment]
I completely agree. I was going through the code and found: https://github.com/marmelab/json-graphql-server/blob/master/src/resolver/Mutation/remove.js

**Comment by pjweisberg** [comment]
And there's the "remove last element" but, too.  Not found, so indexOfEntity is -1, and that's what happens when you pass -1 into Array.splice().

*That*, at least, is easy to fix.

**Comment by a-rcrawford** [comment]
PJ Weisberg's recent merge in fixed the problem of arbitrarily deleting the last item when no such item ID was found.  There is still a problem with not being able to delete IDs specified as strings, but we found that a small change to src/resolver/Mutation/remove.js fixed that bug:

export default (entityData = []) => (_, { id }) => {
    const parsedId = `${id}`;
    const indexOfEntity = entityData.findIndex(e => `${e.id}` === parsedId);
    let removedEntity = undefined;

    if (indexOfEntity !== -1) {
        removedEntity = entityData.splice(indexOfEntity, 1)[0];
    }
    return removedEntity;
};

**Comment by DarkEye123** [comment]
I still have this problem :( Removing existing or non-existing elements causes mentioned behavior and it is very problematic for me
