### ISSUE TITLE
Why db.js?

### ISSUE THREAD

**Issue by m1574b34r** [marmelab/json-graphql-server#70]
Why not just point to a JSON file(s) like json-server?

**Comment by fzaninotto** [comment]
You're asking for a different utility. If you need a graphql server using a REST API as datasource, I guess it already exists (see https://www.prisma.io/).

**Comment by m1574b34r** [comment]
@fzaninotto I think you misunderstand me, I'm just asking why this tool requires the JSON to be in the `db.js` file as an export, rather than the JSON to be simply JSON in a JSON file... The export doesn't seem to add anything worthwhile.

Your README:

```js
module.exports = {
    posts: [
        { id: 1, title: "Lorem Ipsum", views: 254, user_id: 123 },
        { id: 2, title: "Sic Dolor amet", views: 65, user_id: 456 },
    ],
    users: [
        { id: 123, name: "John Doe" },
        { id: 456, name: "Jane Doe" }
    ],
    comments: [
        { id: 987, post_id: 1, body: "Consectetur adipiscing elit", date: new Date('2017-07-03') },
        { id: 995, post_id: 1, body: "Nam molestie pellentesque dui", date: new Date('2017-08-17') }
    ]
}
```

vs. `json-server` README:

Create a `db.json` file with some data

```json
{
  "posts": [
    { "id": 1, "title": "json-server", "author": "typicode" }
  ],
  "comments": [
    { "id": 1, "body": "some comment", "postId": 1 }
  ],
  "profile": { "name": "typicode" }
}
```

It's not a big deal, just seems likely many users like me already have normal JSON files on their system, so it's just a bit of extra work having to format our JSON in this `db.js` file as an export.

**Comment by fzaninotto** [comment]
Did you try putting your data in a JSON file and calling;

```
json-graphql-server db.json
```

?
