### ISSUE TITLE
delete last record instead of given `id`

### ISSUE THREAD

**Issue by eloypnd** [marmelab/json-graphql-server#76]
**What you were expecting:**

When I submit a `remove...` mutation with an `id` of an existing record, this record will be deleted.

**What happened instead:**

The last record was deleted.

**Steps to reproduce:**

- install `json-graphql-server` package with npm/yarn: `yarn add json-graphql-server`
  > will instal last version in [npm registry 2.1.3](https://www.npmjs.com/package/json-graphql-server).
- create a simple `db.js`
- query to list all record
- mutation to remove one record, different than the last one

**Related code:**

```js
# db.js

module.exports = {
  users: [
    {
      id: "asdf",
      name: "John Smith",
      email: "john.smith@email.com"
    },
    {
      id: "qwer",
      name: "John Smith",
      email: "john.smith@email.com"
    },
    {
      id: "zxcv",
      name: "John Smith",
      email: "john.smith@email.com"
    }
  ]
};

```

```
# list all users
query {
  allUsers {
    id
    name
  }
}
```

```
#remove 2nd user
mutation {
  removeUser(id: "qwer")
}
```

**Other information:**

<img width="628" alt="Screen Shot 2019-09-06 at 13 04 19" src="https://user-images.githubusercontent.com/1312803/64423507-ff6d1c00-d0a6-11e9-98de-60adf41535a2.png">
<img width="626" alt="Screen Shot 2019-09-06 at 13 04 37" src="https://user-images.githubusercontent.com/1312803/64423508-ff6d1c00-d0a6-11e9-9f96-2a1e7e533a0f.png">
<img width="626" alt="Screen Shot 2019-09-06 at 13 04 53" src="https://user-images.githubusercontent.com/1312803/64423509-ff6d1c00-d0a6-11e9-8bf9-7dd20e617418.png">

**Environment**

json-graphql-server@2.1.3

macOS 10.13.6
node 10.16.0
yarn 1.17.3

**Comment by activebiz** [comment]
remove mutation looks like is working fine when Id is number. Not sure if it has any thing to do with it or not.

**Comment by plonko** [comment]
I have tried this with numbers and strings and it seems to be quite "random". It's very upsetting.

**Comment by hakanErgin** [comment]
Hi. Any news on this?

**Comment by fzaninotto** [comment]
I believe this has been fixed in master but not yet released:

https://github.com/marmelab/json-graphql-server/pull/68

**Comment by fzaninotto** [comment]
2.2.0 has been published today, it should be fixed now.
