### ISSUE TITLE
New release is overdue

### ISSUE THREAD

**Issue by pixelass** [marmelab/json-graphql-server#83]
While several features and fixes have been added over the last year they have not been released as a new version.

It would be really nice if you could simply publish the current master. (maybe you can tag it as [next] if you don't wan't to publish as stable/[latest])

I am mostly looking for the export schema feature which was added about 5 months ago.

Thank you for your help.

**Comment by pixelass** [comment]
Since this project seems stale, I went ahead and created something similar and in some ways more complete while in others less complete (ATM). I still need to implement several features like filtering and paging but the following features exist:  
* relations work (one-to-many, many-to-one)
* the database can be exported and updated/persisted via mutations
* the generated schema can be exported.

Types are deeply generated, so nested objects will work (with restrictions)

If you're interested you can check out or watch  this project: https://github.com/pixelass/phony

Right now it's just a prototype but a release should follow soon when paging and filtering has been added.

**Comment by pixelass** [comment]
In case anybody is interested: phony has been released https://pixelass.github.io/phony/

**Comment by fzaninotto** [comment]
Check [the releases page](https://github.com/marmelab/json-graphql-server/releases) for a list of recent releases.
