### ISSUE TITLE
Custom port parameter `-p` doesn't work as expected

### ISSUE THREAD

**Issue by rogerclotet** [marmelab/json-graphql-server#85]
**What you were expecting:**
The custom port parameter should be the one defined in the README, `-p`.

**What happened instead:**
This parameter has no effect:

```bash
$ json-graphql-server db.js -p :3001
GraphQL server running with your data at http://localhost:3000/
```

Looking at the code, I noticed the change was added in https://github.com/marmelab/json-graphql-server/commit/fd05e9e320609260de1ba2da1983c7bfb0e64b9c, and the accepted parameter format is `--p`.

**Steps to reproduce:**
Try to run the server with the `-p` parameter with a port different to 3000.

**Related code:**
Commit that introduced the custom port feature: https://github.com/marmelab/json-graphql-server/commit/fd05e9e320609260de1ba2da1983c7bfb0e64b9c

**Other information:**
PR with my suggested changes to add support to `-p` in addition to `--p`: https://github.com/marmelab/json-graphql-server/pull/86

**Comment by fzaninotto** [comment]
I don't understand, the documented way to specify port is --p, why would you use -p?

**Comment by rogerclotet** [comment]
I was certain I read `-p` and I would have sweared I double-checked, but you're right, even though it feels weird having a single-letter flag with two dashes, the readme actually specifies `--p`.

My apologies, closing the issue and PR now.
