### ISSUE TITLE
Is there a way to save the mutations to the db.js file?

### ISSUE THREAD

**Issue by aaronksaunders** [marmelab/json-graphql-server#96]
Apologies for question here, wasn't clear from "contributing guidelines" what the alternative was

I was expecting that changes/mutation to the database would be updated in db.js, any suggestion on how to make that happen. The changes are all  in the InMemoryCache,but there are no updated in the file

**Comment by djhi** [comment]
Please follow the issue template

**Comment by djhi** [comment]
Yes, it is an in memory database. There are no mechanisms in place to export the data.

**Comment by richcorbs** [comment]
I found that I could access the data using this pattern in the "on finish" event:

```
const express = require('express')
const jsonGraphqlExpress = require('json-graphql-server').default

const data = { dogs: [{ id: 1, name: 'pepper' }] };
const app = express();

app.use(function(req, res, next) {
  console.log("before", data);

  res.on("finish", function() {
      console.log("after", data);
  });
  next();
});

app.use('/graphql', jsonGraphqlExpress(data));

const PORT = 5555;
app.listen(PORT, (err) => {
  console.log(`GraphQL server listening on port ${PORT}`)
});
```

Maybe this will help others.
